version: 2

build:
  os: ubuntu-lts-latest
  tools: {python: "3.12"}
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      # TODO: remove when poetry@2 support will be fixed
      - asdf install poetry 1.8.5
      - asdf global poetry 1.8.5
      - poetry config virtualenvs.create false
      - poetry config warnings.export false
      - poetry self add -h
      - poetry export --only main --only docs --format=requirements.txt --output=requirements.txt

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: 'docs/conf.py'
  fail_on_warning: true
