version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
  jobs:
    # See https://github.com/readthedocs/readthedocs.org/issues/4912
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
      - poetry self add poetry-plugin-export
      - poetry export --only main --only docs --format=requirements.txt --output=requirements.txt

sphinx:
  configuration: 'docs/conf.py'
  # TODO: fix warnings and enable
  # fail_on_warning: true
