# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

# See:
# https://wemake-python-styleguide.rtfd.io/en/latest/pages/usage/integrations/nitpick

# This file is included into base-preset.

["setup.cfg".isort]
# These values should be placed inside `setup.cfg` in your repo:
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
